# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveDetail',
            fields=[
                ('id', models.AutoField(db_column='udid', primary_key=True, serialize=False, verbose_name='用户订单关联详情')),
                ('name', models.CharField(db_column='re_name', max_length=100, verbose_name='收货人姓名')),
                ('address', models.CharField(max_length=1000, verbose_name='收货地址')),
                ('tel', models.CharField(db_column='tel_num', max_length=200, verbose_name='收货人电话')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='uid', primary_key=True, serialize=False, verbose_name='用户id')),
                ('name', models.CharField(db_column='username', max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(db_column='password', max_length=255, verbose_name='用户密码')),
                ('email', models.EmailField(db_column='email', max_length=50, verbose_name='用户邮箱')),
                ('img', models.CharField(db_column='img', max_length=1000, null=True, verbose_name='用户头像')),
            ],
        ),
        migrations.AddField(
            model_name='receivedetail',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='关联用户'),
        ),
    ]
